name = "o11a_client"
version = "1.0.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
o11a_common = { path = "../common" }
plinth = { path = "../../plinth" }
gleam_stdlib = ">= 0.59.0 and < 1.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
given = ">= 5.0.4 and < 6.0.0"
gtempo = ">= 7.1.0 and < 8.0.0"
lustre = ">= 5.0.2 and < 6.0.0"
modem = ">= 2.0.2 and < 3.0.0"
snag = ">= 1.1.0 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
lustre_http = { path = "../../lustre_http" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
